package com.cybertek.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

@Entity                         // we dont need to add @Component anymore.. @Entity is enough...
@Table(name= "cars")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class Car {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String make;
    private String model;


    public Car(String make, String model) {   // because id will be generated by Spring we need to add a constructor without id...
        this.make = make;
        this.model = model;
    }
}
